## @knitr txt 
  txt <- function(x, abrv = F, stem = F, term = F) {
    x <- tolower(x)
    
# Abbrev
{   
  if(missing(abrv)|abrv == F){
    x
  } else {
    x <- gsub("(\\<acc\\>|\\<acct\\>)", "account", x)
    x <- gsub("\\<addy\\>", "address", x)
    x <- gsub("\\<adj\\>", "adjust", x)
    x <- gsub("(\\<advd\\>|\\<advsd\\>|\\<advisd\\>)", "advised", x)
    x <- gsub("\\<amazoncom\\>", "amazon", x)
    x <- gsub("\\<amt\\>", "amount", x)
    x <- gsub("\\<alrt\\>", "alert", x)
    x <- gsub("\\<ar\\>", "accounts_receivable", x)
    x <- gsub("\\<assem\\>", "assembly", x)
    x <- gsub("\\<auth\\>", "authorization", x)
    x <- gsub("\\<avail\\>", "available", x)
    x <- gsub("\\<bck\\>", "back", x)
    x <- gsub("\\<bus\\>", "business", x)
    x <- gsub("\\<bx\\>", "box", x)
    x <- gsub("\\<ccd\\>", "credit_card", x)
    x <- gsub("(\\<chg\\>|\\<chng\\>)", "change", x)   
    x <- gsub("\\<chgd\\>", "changed", x)   
    x <- gsub("(\\<chrg\\>|\\<chrge\\>)", "charge", x)    
    x <- gsub("(\\<cking\\>|\\<ckg\\>)", "checking", x)    
    x <- gsub("\\<cld\\>", "called", x)
    x <- gsub("\\<complaints\\>", "compliant", x)
    x <- gsub("\\<conf\\>", "confirm", x)
    x <- gsub("\\<corrected\\>", "correct", x)
    x <- gsub("(\\<cou\\>|\\<cour\\>)", "courier", x)
    x <- gsub("\\<cncl\\>", "cancel", x)
    x <- gsub("\\<cx\\>", "customer", x)
    x <- gsub("(\\<cxld\\>|\\<cncld\\>)", "cancelled", x)
    x <- gsub("(\\<cp\\>|\\<cpn\\>|\\<coup\\>)", "coupon", x)
    x <- gsub("(\\<cps\\>|\\<cpns\\>)", "coupons", x)    
    x <- gsub("\\<crtsy\\>", "courtesy", x)
    x <- gsub("\\<cracked\\>", "crack", x)
    x <- gsub("(\\<cr\\>|\\<crd\\>|\\<crdit\\>|\\<crdt\\>)", "credit", x)
    x <- gsub("(\\<crushed\\>|\\<crushing\\>)", "crush", x)
    x <- gsub("(\\<cx\\>|\\<cust\\>|\\<cst\\>|\\<csut\\>)", "customer", x)  
    x <- gsub("\\<cxl\\>", "cancel", x)
    x <- gsub("\\<decl\\>", "decline", x)
    x <- gsub("(\\<dented\\>|\\<dents\\>)", "dent", x)
    x <- gsub("(\\<del\\>|\\<dlv\\>|\\<dlvr\\>|\\<delv\\>|\\<deliv\\>)", "deliver", x) 
    x <- gsub("(\\<dlvd\\>|\\<delvd\\>|\\<dlvrd\\>|\\<dlved\\>)", "delivered", x)
    x <- gsub("(\\<dlvy\\>|\\<dlvry\\>)", "delivery", x)      
    x <- gsub("\\<dept\\>", "department", x)    
    x <- gsub("\\<dnt\\>", "didnt", x) 
    x <- gsub("\\<diff\\>", "different", x)    
    x <- gsub("(\\<dmg\\>|\\<dmgd\\>)", "damage", x)    
    x <- gsub("\\<drvr\\>", "driver", x)
    x <- gsub("\\<dup\\>", "duplicate", x)
    x <- gsub("\\<ee\\>", "even_exchange", x)
    x <- gsub("\\<env\\>", "envelope", x)
    x <- gsub("\\<em\\>", "email", x)
    x <- gsub("\\<esd\\>", "electronic_software_download", x)  
    x <- gsub("(\\<exc\\>|\\<excep\\>)", "exception", x)
    x <- gsub("(\\<exchg\\>|\\<exch\\>)", "exchange", x)  
    x <- gsub("\\<exchngs\\>", "exchanges", x)  
    x <- gsub("\\<exchng\\>", "exchanging", x)
    x <- gsub("\\<ee\\>", "even_exchange", x)
    x <- gsub("\\<evn\\>", "even", x)    
    x <- gsub("\\<exp\\>", "expire", x)
    x <- gsub("\\<exmpt\\>", "exempt", x)   
    x <- gsub("\\<fc\\>", "fulfillment_center", x)
    x <- gsub("\\<fnd\\>", "find", x)
    x <- gsub("\\<frd\\>", "fraud", x)
    x <- gsub("\\<furn\\>", "furniture", x)
    x <- gsub("\\<hld\\>", "hold", x)  
    x <- gsub("\\<hlf\\>", "fraud_hold", x)  
    x <- gsub("\\<ima\\>", "invoice_my_account", x)    
    x <- gsub("\\<info\\>", "information", x)
    x <- gsub("(\\<inq\\>|\\<inqr\\>)", "inquiry", x)
    x <- gsub("\\<inv\\>", "invoice", x)
    x <- gsub("\\<itm\\>", "item", x)
    x <- gsub("\\<itms\\>", "items", x)   
    x <- gsub("(\\<lbl\\>|\\<labl\\>)", "label", x)
    x <- gsub("\\<lbls\\>", "labels", x) 
    x <- gsub("\\<lqo\\>", "large_quantity_order", x)    
    x <- gsub("\\<mbr\\>", "member", x)    
    x <- gsub("(\\<mfr\\>|\\<mfg\\>|\\<mfgr\\>)", "manufacture", x)    
    x <- gsub("(\\<mp\\>|\\<mispck\\>)", "mispick", x)
    x <- gsub("\\<mop\\>", "method_of_payment", x)
    x <- gsub("\\<mgr\\>", "manager", x)    
    x <- gsub("\\<nd\\>", "second", x)    
    x <- gsub("\\<nsp\\>", "nonstock_procurement", x)
    x <- gsub("(\\<npn\\>|\\<nopu\\>|\\<no pu\\>)", "no_pickup", x)
    x <- gsub("\\<nvr\\>", "never", x)
    x <- gsub("\\<odt\\>", "on_delivery_truck", x)    
    x <- gsub("\\<oos\\>", "out of stock", x)
    x <- gsub("\\<ofd\\>", "out_for_delivery", x)
    x <- gsub("\\<orc\\>", "online_return_center", x)
    x <- gsub("(\\<ord\\>|\\<ordr\\>)", "order", x)
    x <- gsub("\\<ordrd\\>", "ordered", x)
    x <- gsub("\\<org\\>", "original", x)
    x <- gsub("\\<ovrrde\\>", "override", x)    
    x <- gsub("\\<pck\\>", "pick", x)
    x <- gsub("(\\<pckd\\>|\\<pcked\\>)", "picked", x)
    x <- gsub("\\<pcking\\>", "picking", x)
    x <- gsub("\\<pd\\>", "paid", x)
    x <- gsub("\\<ph\\>", "phone", x) 
    x <- gsub("\\<pkg\\>>", "package", x)
    x <- gsub("(\\<pckg\\>|\\<pckng\\>|\\<pkng\\>)", "packing", x)   
    x <- gsub("\\<plcy\\>", "policy", x)    
    x <- gsub("(\\<pp\\>|\\<ppd\\>|\\<prepd\\>)", "prepaid", x)
    x <- gsub("\\<ppr\\>", "paper", x) 
    x <- gsub("\\<prev\\>", "previous", x)
    x <- gsub("(\\<prm\\>|\\<promo\\>)", "promotion", x)
    x <- gsub("\\<prod\\|\\<prdct\\>>", "product", x)    
    x <- gsub("\\<pu\\>>", "pickup", x)
    x <- gsub("\\<purch\\>", "purchase", x)
    x <- gsub("\\<pwd\\>", "password", x)
    x <- gsub("\\<pymnt\\>", "payment", x)
    x <- gsub("\\<qty\\>", "quantity", x)
    x <- gsub("(\\<rec\\>|\\<rcv\\>|\\<recv\\>)", "receive", x)
    x <- gsub("(\\<recd\\>|\\<rcvd\\>|\\<rcved\\>|\\<revcd\\>|\\<recvd\\>|\\<rvcd\\>)", "received", x)
    x <- gsub("\\<ref\\>", "refer", x)    
    x <- gsub("\\<reg\\>", "register", x)  
    x <- gsub("\\<rel\\>", "release", x)
    x <- gsub("\\<reord\\>", "reorder", x)      
    x <- gsub("\\<repl\\>", "replace", x)
    x <- gsub("(\\<req\\>|\\<rqst\\>|\\<reqst\\>)", "request", x)
    x <- gsub("(\\<rfd\\>|\\<rfn\\>|\\<rfnd\\>)", "refund", x)
    x <- gsub("(\\<rshp\\>|\\<reshp\\>)", "reship", x)
    x <- gsub("(\\<rt\\>|\\<ret\\>|\\<rtn\\>|\\<retn\\>|\\<rtrn\\>|\\<retrn\\>)", "return", x)
    x <- gsub("(\\<retnd\\>|\\<rtnd\\>|\\<rtrnd\\>)", "returned", x)
    x <- gsub("(\\<rtrning\\>|\\<rtning\\>)", "returning", x)
    x <- gsub("(\\<rew\\>|\\<rwd\\>)", "reward", x)
    x <- gsub("(\\<rews\\>|\\<rwds\\>|\\<rwrds\\>)", "rewards", x)
    x <- gsub("\\<sam\\>", "staples_account_manager", x)
    x <- gsub("\\<sbg\\>", "staples_brand_group", x)
    x <- gsub("\\<sdr\\>", "stop_delivery_request", x)
    x <- gsub("(\\<sch\\>|\\<sche\\>)", "schedule", x)
    x <- gsub("\\<scr\\>", "scratch", x)
    x <- gsub("\\<snt\\>", "sent", x)
    x <- gsub("(\\<stk\\>|\\<stck\\>)", "stock", x) 
    x <- gsub("\\<stp\\>", "stop", x)
    x <- gsub("\\<ste\\>", "suite", x)
    x <- gsub("\\<sup\\>", "supervisor", x)
    x <- gsub("\\<sys\\>", "system", x)
    x <- gsub("\\<svgs\\>", "savings", x)
    x <- gsub("\\<sz\\>", "size", x)    
    x <- gsub("(\\<tc\\>|\\<tcc\\>)", "first_time_courtsey_coupon", x)
    x <- gsub("\\<tcp\\>", "told_customer_policy", x)   
    x <- gsub("\\<tnr\\>", "toner", x)       
    x <- gsub("(\\<trns\\>|\\<trsf\\>|\\<trans\\>|\\<xfr\\>|\\<xfer\\>|\\<trxfr\\>|\\<trnsfr\\>|\\<trxfer\\>|\\<xnfer\\>)", "transfer", x)
    x <- gsub("\\<vndr\\>", "vendor", x) 
    x <- gsub("\\<wnt\\>", "want", x) 
    x <- gsub("\\<wnted\\>", "wanted", x)       
    x <- gsub("(\\<wrg\\>|\\<wrng\\>)", "wrong", x)    
    x <- gsub("\\<wyf\\>", "wayfair", x) 
    x <- gsub("(\\<xnsferred\\>|\\<xnsfer\\>|\\<xfrd\\>|\\<xnfered\\>)", "transferred", x)      
    x <- gsub("\\<xchng\\>", "exchange", x)
  }
}

  # Stemming
{     
  if(missing(stem)|stem==F){
    x
  } else {
      x <- gsub("(\\<added\\>|\\<adding\\>)", "add", x)
      x <- gsub("\\<accepted\\>", "accept", x)
      x <- gsub("\\<adjusted\\>|\\<adjusting\\>", "adjust", x)
      x <- gsub("(\\<advised\\>|\\<advising\\>)", "advise", x)
      x <- gsub("(\\<alerting\\>|\\<alerted\\>)", "alert", x)
      x <- gsub("(\\<allowed\\>|\\<allowing\\>)", "allow", x)
      x <- gsub("\\<answered\\>", "answer", x)
      x <- gsub("(\\<applied\\>|\\<applying\\>)", "apply", x)
      x <- gsub("\\<approved\\>", "approve", x)
      x <- gsub("(\\<arrived\\>|\\<arriving\\>|\\<arrives\\>)", "arrive", x)
      x <- gsub("(\\<asked\\>|\\<asking\\>)", "ask", x)
      x <- gsub("\\<assembled\\>", "assembly", x)
      x <- gsub("(\\<assisted\\>|\\<assist\\>)", "ask", x)
      x <- gsub("(\\<attempted\\>|\\<attempts\\>)", "attempt", x)
      x <- gsub("\\<backordered\\>", "backorder", x)
      x <- gsub("\\<billed\\>", "bill", x)
      x <- gsub("\\<binders\\>", "binder", x)
      x <- gsub("\\<broken\\>", "broke", x)
      x <- gsub("\\<cabinets\\>", "cabinet", x)
      x <- gsub("\\<cameras\\>", "camera", x)
      x <- gsub("\\<calculators\\>", "calculator", x)
      x <- gsub("(\\<called\\>|\\<calling\\>)", "call", x)
      x <- gsub("(\\<cancelled\\>|\\<canceled\\>)", "cancel", x)
      x <- gsub("\\<cartridges\\>", "cartridge", x)
      x <- gsub("\\<carts\\>", "cart", x)
      x <- gsub("\\<chairs\\>", "chair", x)
      x <- gsub("\\<chairmats\\>", "chairmat", x)
      x <- gsub("(\\<changed\\>|\\<changing\\>)", "change", x)
      x <- gsub("(\\<charged\\>|\\<charging\\>|\\<charges\\>)", "charge", x)
      x <- gsub("(\\<checked\\>|\\<checking\\>)", "check", x)
      x <- gsub("\\<closed\\>", "close", x)
      x <- gsub("\\<codes\\>", "code", x)
      x <- gsub("\\<completed\\>", "complete", x)
      x <- gsub("\\<computers\\>", "computer", x)
      x <- gsub("(\\<confirmed\\>|\\<confirming\\>)", "confirm", x)    
      x <- gsub("\\<connected\\>", "connect", x)
      x <- gsub("\\<contacted\\>", "contact", x)
      x <- gsub("\\<copied\\>", "copy", x)
      x <- gsub("\\<coupons\\>", "coupon", x)
      x <- gsub("\\<created\\>", "create", x)
      x <- gsub("\\<credited\\>", "credit", x)
      x <- gsub("\\<customers\\>", "customer", x)
      x <- gsub("\\<damaged\\>", "damage", x)
      x <- gsub("\\<deactivated\\>", "deactivate", x)
      x <- gsub("\\<decided\\>", "decide", x)
      x <- gsub("\\<declined\\>", "decline", x)
      x <- gsub("\\<delayed\\>", "delay", x)
      x <- gsub("\\<deleted\\>", "delete", x)
      x <- gsub("\\<delivered\\>", "deliver", x)
      x <- gsub("\\<denied\\>", "deny", x)
      x <- gsub("(\\<directed\\>|\\<directing\\>)", "direct", x)
      x <- gsub("\\<disconnected\\>", "disconnect", x)
      x <- gsub("\\<discounted\\>", "discount", x)
      x <- gsub("\\<disks\\>", "disk", x)
      x <- gsub("(\\<downloads\\>|\\<downloaded\\>|\\<downloading\\>)", "download", x)
      x <- gsub("\\<drivers\\>", "driver", x)
      x <- gsub("\\<dropped\\>", "drop", x)
      x <- gsub("\\<duplicated\\>", "duplicate", x)
      x <- gsub("\\<educated\\>", "educate", x)
      x <- gsub("(\\<emailed\\>|\\<emails\\>)", "email", x)
      x <- gsub("\\<entered\\>", "enter", x)
      x <- gsub("\\<envelopes\\>", "envelope", x)
      x <- gsub("\\<errors\\>", "error", x)
      x <- gsub("\\<estimated\\>", "estimate", x)
      x <- gsub("\\<exceptions\\>", "exception", x)
      x <- gsub("(\\<exchanges\\>|\\<exchanged\\>|\\<exchanging\\>)", "exchange", x)
      x <- gsub("\\<expected\\>", "expect", x)
      x <- gsub("\\<expectations\\>", "expectation", x)
      x <- gsub("(\\<expired\\>|\\<expires\\>)", "expire", x)
      x <- gsub("\\<explained\\>", "explain", x)
      x <- gsub("(\\<faxed\\>|\\<faxing\\>)", "fax", x)
      x <- gsub("\\<fees\\>", "fee", x)
      x <- gsub("\\<filled\\>", "fill", x)
      x <- gsub("\\<finding\\>", "find", x)
      x <- gsub("\\<finished\\>", "finish", x)
      x <- gsub("\\<fixed\\>", "fix", x)
      x <- gsub("\\<folders\\>", "folder", x)
      x <- gsub("\\<forwarded\\>", "forward", x)
      x <- gsub("(\\<handled\\>|\\<handles\\>|\\<handling\\>)", "handle", x)
      x <- gsub("(\\<helps\\>|\\<helped\\>|\\<helping\\>)", "help", x)
      x <- gsub("\\<holders\\>", "holder", x)
      x <- gsub("\\<included\\>", "include", x)
      x <- gsub("\\<incorrectly\\>", "incorrect", x)
      x <- gsub("\\<informed\\>", "inform", x)
      x <- gsub("\\<inks\\>", "ink", x)
      x <- gsub("(\\<inquired\\>|\\<inquiring\\>)", "inquiry", x)    
      x <- gsub("\\<installed\\>", "install", x)
      x <- gsub("(\\<invoices\\>|\\<invoiced\\>)", "invoice", x)
      x <- gsub("(\\<issued\\>|\\<issued\\>)", "issue", x)
      x <- gsub("\\<instructions\\>", "instruction", x)
      x <- gsub("\\<items\\>", "item", x)
      x <- gsub("\\<kcups\\>", "kcup", x)
      x <- gsub("(\\<keeping\\>|\\<keeps\\>|\\<kept\\>)", "keep", x)
      x <- gsub("\\<keys\\>", "key", x)
      x <- gsub("\\<labels\\>", "label", x)
      x <- gsub("(\\<leaking\\>|\\<leaks\\>|\\<leaked\\>)", "leak", x)
      x <- gsub("\\<listed\\>", "list", x)
      x <- gsub("(\\<located\\>|\\<locating\\>)", "locate", x)
      x <- gsub("(\\<looked\\>|\\<looking\\>)", "look", x)
      x <- gsub("\\<mailed\\>", "mail", x)
      x <- gsub("(\\<mispicked\\>|\\<misspick\\>)", "mispick", x)
      x <- gsub("(\\<needs\\>|\\<needed\\>|\\<needing\\>)", "need", x)
      x <- gsub("\\<noted\\>", "note", x)
      x <- gsub("\\<notified\\>", "notify", x)
      x <- gsub("\\<offered\\>", "offer", x)
      x <- gsub("(\\<opened\\>|\\<opening\\>|\\<opens\\>)", "open", x)
      x <- gsub("\\<options\\>", "option", x)
      x <- gsub("(\\<ordered\\>|\\<ordering\\>)", "order", x)
      x <- gsub("\\<overiding\\>", "override", x)
      x <- gsub("\\<packages\\>", "package", x)
      x <- gsub("\\<pens\\>", "pen", x)
      x <- gsub("\\<pencils\\>", "pencil", x)
      x <- gsub("(\\<picked\\>|\\<picking\\>)", "pick", x)
      x <- gsub("(\\<placed\\>|\\<placing\\>)", "place", x)
      x <- gsub("\\<posted\\>", "post", x)
      x <- gsub("\\<powered\\>", "power", x)
      x <- gsub("\\<pretzels\\>", "pretzel", x)
      x <- gsub("(\\<priced\\>|\\<pricing\\>)", "price", x)
      x <- gsub("\\<printed\\>", "print", x)
      x <- gsub("\\<printers\\>", "printer", x)
      x <- gsub("\\<problems\\>", "problem", x)
      x <- gsub("(\\<processed\\>|\\<processing\\>)", "process", x)
      x <- gsub("(\\<provided\\>|\\<providing\\>)", "provide", x)
      x <- gsub("(\\<pulled\\>|\\<pulling\\>|\\<pulls\\>)", "pull", x)
      x <- gsub("(\\<purchased\\>|\\<purchasing\\>)", "purchase", x)
      x <- gsub("\\<questions\\>", "question", x)
      x <- gsub("\\<rebates\\>", "rebate", x)
      x <- gsub("(\\<received\\>|\\<recieved\\>|\\<recieving\\>)", "receive", x)
      x <- gsub("(\\<recycling\\>|\\<recycled\\>)", "recycle", x)
      x <- gsub("\\<referred\\>", "refer", x)
      x <- gsub("\\<refills\\>", "refill", x)
      x <- gsub("(\\<refunded\\>|\\<refunds\\>)", "refund", x)
      x <- gsub("\\<refused\\>", "refuse", x)
      x <- gsub("\\<registered\\>", "register", x)
      x <- gsub("\\<reissued\\>", "reissue", x)
      x <- gsub("(\\<replaced\\>|\\<replacing\\>|\\<replacement\\>)", "replace", x)
      x <- gsub("\\<rejected\\>", "reject", x)
      x <- gsub("\\<reams\\>", "ream", x)
      x <- gsub("(\\<removed\\>|\\<removing\\>)", "remove", x)
      x <- gsub("\\<released\\>", "release", x)
      x <- gsub("\\<reordered\\>", "reorder", x)
      x <- gsub("\\<reported\\>", "report", x)
      x <- gsub("\\<requested\\>", "request", x)
      x <- gsub("\\<requesting\\>", "request", x)
      x <- gsub("\\<resend\\>", "resent", x)
      x <- gsub("\\<resolved\\>", "resolve", x)
      x <- gsub("\\<reshipped\\>", "reship", x)
      x <- gsub("\\<resubmitted\\>", "resubmit", x)
      x <- gsub("\\<required\\>", "require", x)
      x <- gsub("(\\<returned\\>|\\<returning\\>)", "return", x)
      x <- gsub("\\<savings\\>", "saving", x)
      x <- gsub("\\<scratched\\>", "scratch", x)
      x <- gsub("(\\<sending\\>|\\<send\\>)", "sent", x)
      x <- gsub("\\<shipped\\>", "ship", x)
      x <- gsub("(\\<shows\\>|\\<showed\\>|\\<showing\\>|\\<shown\\>)", "show", x)
      x <- gsub("\\<shredders\\>", "shredder", x)
      x <- gsub("\\<signed\\>", "sign", x)
      x <- gsub("\\<slips\\>", "slip", x)
      x <- gsub("(\\<spelled\\>|\\<spelling\\>)", "spell", x)
      x <- gsub("\\<staplers\\>", "stapler", x)
      x <- gsub("(\\<stated\\>|\\<stating\\>|\\<states\\>)", "state", x)
      x <- gsub("\\<stopped\\>", "stop", x)
      x <- gsub("(\\<submitted\\>|\\<submitting\\>)", "submit", x)
      x <- gsub("\\<switched\\>", "switch", x)
      x <- gsub("(\\<taken\\>|\\<takes\\>|\\<taking\\>)", "take", x)
      x <- gsub("\\<taxes\\>", "tax", x)
      x <- gsub("(\\<thanked\\>|\\<thanks\\>)", "thank", x)
      x <- gsub("(\\<trying\\>|\\<tried\\>)", "try", x)
      x <- gsub("(\\<transferred\\>|\\<transfered\\>)", "transfer", x)
      x <- gsub("(\\<updated\\>|\\<updating\\>)", "update", x)
      x <- gsub("(\\<using\\>|\\<used\\>|\\<uses\\>)", "use", x)
      x <- gsub("(\\<verified\\>|\\<verifying\\>)", "verify", x)
      x <- gsub("(\\<waited\\>|\\<waiting\\>)", "wait", x)
      x <- gsub("(\\<wants\\>|\\<wanted\\>|\\<wanting\\>)", "want", x)
      x <- gsub("(\\<wondering\\>|\\<wondered\\>)", "wonder", x)
      x <- gsub("(\\<working\\>|\\<worked\\>|\\<works\\>)", "work", x)
    }
}

  # Terms
{
  if(missing(term)|term==F){
      x
  } else {
      x <- gsub("(\\<address change\\>|\\<update address\\>)", "change_address", x)
      x <- gsub("\\<as400\\>", "asfourhundred", x)
      x <- gsub("\\<billing address\\>", "billing_address", x)
      x <- gsub("\\<call back\\>", "call_back", x)
      x <- gsub("\\<change address\\>", "change_address", x)
      x <- gsub("\\<coms rep\\>", "coms_rep", x)
      x <- gsub("\\<copy and print\\>", "copyprint", x)
      x <- gsub("\\<copy of invoice\\>", "copy_of_invoice", x)    
      x <- gsub("\\<coupon code\\>", "coupon_code", x)
      x <- gsub("(\\<courtesy coupon\\>|\\<courtesy coupons\\>)", "courtesy_coupon", x)
      x <- gsub("\\<credit card\\>", "credit_card", x)
      x <- gsub("\\<customer number\\>", "customer_number", x)
      x <- gsub("\\<cyber agent\\>", "cyber_agent", x)
      x <- gsub("\\<daily deal\\>", "dailydeal", x)
      x <- gsub("(\\<delivery address\\>|\\<deliver address\\>)", "delivery_address", x)
      x <- gsub("\\<down load\\>", "download", x)
      x <- gsub("\\<drop ship\\>", "drop_ship", x)
      x <- gsub("\\<easy tech\\>", "easytech", x)
      x <- gsub("\\<email address\\>", "email_address", x)
      x <- gsub("\\<even exchange\\>", "even_exchange", x)
      x <- gsub("\\<fraud hold\\>", "fraud_hold", x)
      x <- gsub("(\\<gift card\\>|\\<gift cards\\>)", "giftcard", x)
      x <- gsub("\\<ink recycle\\>", "ink_recycling", x)
      x <- gsub("\\<instant saving\\>", "instant_saving", x)
      x <- gsub("\\<ipad mini\\>", "ipad_mini", x)
      x <- gsub("\\<kana case\\>", "kana_case", x)
      x <- gsub("\\<k cups\\>", "kcups", x)
      x <- gsub("\\<kindle fire\\>", "kindle_fire", x)
      x <- gsub("\\<log in\\>", "login", x)  
      x <- gsub("\\<new customer\\>", "new_customer", x)
      x <- gsub("\\<order place\\>", "place_order", x)
      x <- gsub("\\<out of stock\\>", "out_of_stock", x)
      x <- gsub("(\\<pack slip\\>|\\<packing slip\\>)", "packing_slip", x)
      x <- gsub("\\<phone number\\>", "phone_number", x)
      x <- gsub("\\<pick(|ed) up\\>", "pickup", x)
      x <- gsub("\\<place order\\>", "place_order", x)
      x <- gsub("\\<po box\\>", "po_box", x)  
      x <- gsub("\\<price match\\>", "price_match", x)
      x <- gsub("\\<prepaid exception\\>", "prepaid_exception", x)
      x <- gsub("\\<product key\\>", "productkey", x)
      x <- gsub("\\<return label\\>", "return_label", x)
      x <- gsub("\\<sam rep\\>", "sam_rep", x)
      x <- gsub("\\<service failure\\>", "service_failure", x)
      x <- gsub("\\<set up\\>", "setup", x)
      x <- gsub("\\<shipping address\\>", "shipping_address", x)
      x <- gsub("(\\<staples adv\\>|\\<staples advantage\\>)", "staples_advantage", x)
      x <- gsub("\\<staples brand group\\>", "staples_brand_group", x)
      x <- gsub("(\\<stop delivery\\>|\\<stop delivery request\\>)", "stop_delivery_request", x)
      x <- gsub("\\<store compliant\\>", "store_compliant", x)
      x <- gsub("\\<store only\\>", "store_only", x)
      x <- gsub("\\<store stock\\>", "store_stock", x)
      x <- gsub("\\<tax hold\\>", "tax_hold", x)
      x <- gsub("\\<tax exempt\\>", "tax_exempt", x)
      x <- gsub("\\<tech support\\>", "tech_support", x)   
      x <- gsub("\\<turbo tax\\>", "turbotax", x)   
      x <- gsub("\\<usb cable\\>", "usb_cable", x)  
      x <- gsub("\\<uneven exchange\\>", "uneven_exchange", x)
      x <- gsub("\\<ups label\\>", "ups_label", x)   
      x <- gsub("\\<ups store\\>", "ups_store", x)
      x <- gsub("\\<web tech\\>", "webtech", x)
      x <- gsub("\\<windows 7\\>", "windows_seven", x)
      x <- gsub("(\\<windows 81\\>|\\<windows 8\\>)", "windows_eight", x)
      x <- gsub("\\<windows 10\\>", "windows_ten", x)
      x <- gsub("\\<windows xp\\>", "windows_xp", x)
      x <- gsub("\\<wrong address\\>", "wrong_address", x)      
      x <- gsub("\\<wrong item(|s)\\>", "wrong_item", x)
      x <- gsub("\\<zip code\\>", "zip_code", x)
    }
}

# Spelling

#lable cancelation canceld deffective deliveried proccess proccessed transferd vender




}
  
  
